### ISSUE TITLE
Using chained method call produce code using temporary vars

### ISSUE THREAD

**Issue by didos36** [LorenzoBettini/jbase#45]
When I'm writting this
`StringBuilder strBuilder = new StringBuilder();
strBuilder.append("foo").append("bar");
String res = strBuilder.toString();`
I got this:
`StringBuilder strBuilder = new StringBuilder();
 StringBuilder _append = strBuilder.append("foo");
  _append.append("bar");
  String res = strBuilder.toString();`

Is it possible to remove var with prefix "_" when using chained method call?

**Comment by LorenzoBettini** [comment]
Hi
That's the standard Xbase compilation strategy and it's crucial to have debug working correctly for your DSL, so the additional variables with intermediate results need to be generated.
Why do you want to remove them in the generated code? They do not add any overhead, and in the end the generated code should not be necessarily inspected ;)

**Comment by didos36** [comment]
Thanks for your answer, but we'd like to hide xtext model file from our final release to our customer and deliver only generated stuff...I know this is not the purpose of xbase, and maybe be stupid but this is some "strategic" choices...
Is it possible to change naming strategy for theses temp var?

**Comment by LorenzoBettini** [comment]
So you only want to change the names of additional variables generated by the Xbase compiler?
You have to look at the Xbase (and Jbase) compiler code to hook your custom variable name generation strategy. Please keep in mind that the name generation strategy in Xbase will take care to possibly add suffixes to variable names to avoid having duplicate variables. You should keep this strategy, or you'll get in troubles :)

In any case, please keep in mind that generated code is not meant to be readable... Xbase does a very good job in keeping the generated Java code readable, but you should not expect it to be as you would write that manually :)

The other possibility is to have an option in Jbase so that it simply generates the original Java expression code in the generated code... this should be used ONLY for deliver generated code, which will NOT be debuggable.

**Comment by didos36** [comment]
Having an option using Jbase to "simply" generates the original java expression is my best choice of course. But is it easy to do?

**Comment by LorenzoBettini** [comment]
What I could try to do is provide an additional compiler (probably a custom JvmModelGenerator) that does that. Then it will be your responsibility to bind such a custom generator in your Guice module, before releasing.

For sure, you'll have to write a well-done test suite will be required to make sure that the behavior of the two generated code are the same :)

**Comment by didos36** [comment]
That could be nice. thanks a lot.

**Comment by LorenzoBettini** [comment]
Did you see that in new versions of Xtext the number of lines (and temporary variables) has been reduced a lot?

**Comment by LorenzoBettini** [comment]
I think we can close this one now
